name: Run Postman Tests

on: [push]

jobs:
  newman-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # or your required Node.js version

      - name: Install Dependencies
        run: npm install -g newman newman-reporter-htmlextra

      - name: Run Newman Tests
        run: newman run "Weatherstack.postman_collection.json" -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html
